### ISSUE TITLE
Add `force` option

### ISSUE THREAD

**Issue by notlmn** [fregante/daily-version-action#13]
Example:

``` yaml
Version:
    steps:
    - uses: actions/checkout@v2
    - name: Create tag if necessary
      uses: fregante/daily-version-action@v1
      with:
        force: true
```

This would create a tag, even when the `HEAD` is already tagged. Could be used for manual retry deployments (Eg: https://github.com/notlmn/browser-extension-template/issues/32).
