### ISSUE TITLE
Option: Create output but not git tag

### ISSUE THREAD

**Issue by fregante** [fregante/daily-version-action#25]
I'd like to perform additional tasks before creating the tag or maybe use a separate action to create and submit it. Example:

```yml
  Version:
    steps:
    - uses: actions/checkout@v2
    - name: Should release?
      uses: fregante/daily-version-action@v2
      with:
        create-git-tag: false
    - if: env.DAILY_VERSION_CREATED
      run: npm version $DAILY_VERSION
```

Maybe it should be called `dry-run`
