### ISSUE TITLE
Disable tagging/pushing optionally

### ISSUE THREAD

**Issue by fregante** [fregante/daily-version-action#6]
It could accept inputs to make it a plain **getter** action. Successive steps/jobs can use its outputs.

```yml
Version:
  steps:
    - uses: actions/checkout@v2
    - name: Create tag if necessary
      uses: fregante/daily-version-action@v1
        with:
          tag: false
          push: false
```

**Comment by fregante** [comment]
Nevermind. One can just use [`daily-version`](https://github.com/fregante/daily-version) for that. Probably just:

```yml
Version:
  steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=version::`npx daily-version`
```
